"""Authentication commands: login, logout, status, me."""

from __future__ import annotations

import json
import logging

import click
from rich.markup import escape
from rich.panel import Panel
from rich.table import Table

from ..resume import normalize_resume
from ._common import (
    console,
    handle_command,
    require_auth,
    structured_output_options,
)

logger = logging.getLogger(__name__)


@click.command()
@click.option("--qrcode", is_flag=True, help="使用二维码扫码登录")
@click.option("--cookie-source", default=None, help="指定浏览器 (chrome/firefox/edge/brave/arc/safari等)")
def login(qrcode: bool, cookie_source: str | None) -> None:
    """扫码登录 Boss 直聘 APP"""
    from ..auth import clear_credential, verify_credential

    def _finalize_login(cred, *, from_qr: bool = False) -> None:
        # QR login cannot obtain __zp_stoken__ (generated by JS).
        # If only that cookie is missing, accept the credential with a warning
        # instead of failing the full API verification.
        if from_qr and not cred.has_required_cookies:
            missing = cred.missing_required_cookies
            if missing == ["__zp_stoken__"]:
                console.print(f"[green]✅ 登录成功！[/green] ({len(cred.cookies)} cookies)")
                console.print(
                    "[yellow]⚠️  __zp_stoken__ 缺失（该 cookie 由浏览器 JS 生成，QR 登录无法获取）。\n"
                    "   部分接口可能返回「环境异常」，建议用浏览器登录后再执行 boss login 补全。[/yellow]"
                )
                return

        authenticated, message = verify_credential(cred, force_refresh=True)
        if authenticated:
            console.print(f"[green]✅ 登录成功！[/green] ({len(cred.cookies)} cookies)")
            return
        clear_credential()
        console.print("[red]❌ 登录失败：凭证未通过实际接口校验[/red]")
        if message:
            console.print(f"[dim]{message}[/dim]")
        if not from_qr:
            console.print(
                "\n[yellow]💡 提示：浏览器运行时 Cookie 可能未写入磁盘，建议：\n"
                "   1. 关闭浏览器后重试 boss login\n"
                "   2. 或使用 boss login --qrcode 扫码登录[/yellow]"
            )
        raise SystemExit(1)

    if qrcode:
        # Prefer browser-assisted login (captures __zp_stoken__ via JS)
        # Fallback to HTTP-only QR flow when camoufox is unavailable
        try:
            from ..browser_login import browser_qr_login, BrowserLoginUnavailable
            try:
                cred = browser_qr_login()
                _finalize_login(cred, from_qr=True)
                return
            except BrowserLoginUnavailable as e:
                console.print(
                    f"[yellow]⚠️  浏览器辅助登录不可用: {e}\n"
                    "   安装方式: pip install 'kabi-boss-cli[browser]' && python -m camoufox fetch\n"
                    "   回退到 HTTP 扫码登录...[/yellow]\n"
                )
        except ImportError:
            pass

        # Fallback: HTTP-only QR login
        from ..auth import qr_login
        import asyncio
        try:
            cred = asyncio.run(qr_login())
        except RuntimeError as e:
            console.print(f"[red]❌ {e}[/red]")
            raise SystemExit(1) from None
        _finalize_login(cred, from_qr=True)
    else:
        from ..auth import extract_browser_credential, _diagnose_extraction_issues
        # Try browser cookies first
        cred, diagnostics = extract_browser_credential(cookie_source=cookie_source)
        if cred:
            _finalize_login(cred)
        else:
            # Show diagnostics hint if available
            hint = _diagnose_extraction_issues(diagnostics)
            if hint:
                console.print("[yellow]⚠️  Cookie 提取诊断:[/yellow]")
                for line in hint.splitlines():
                    console.print(f"  [dim]{line}[/dim]")
                console.print()

            # Fallback to QR login
            console.print("[yellow]未找到浏览器 Cookie，尝试二维码登录...[/yellow]")
            console.print("[dim]💡 也可以手动设置 BOSS_COOKIES 环境变量来注入 cookie[/dim]")
            try:
                from ..browser_login import browser_qr_login, BrowserLoginUnavailable
                try:
                    cred = browser_qr_login()
                    _finalize_login(cred, from_qr=True)
                    return
                except BrowserLoginUnavailable:
                    pass
            except ImportError:
                pass

            from ..auth import qr_login
            import asyncio
            try:
                cred = asyncio.run(qr_login())
            except RuntimeError as e:
                console.print(f"[red]❌ {e}[/red]")
                raise SystemExit(1) from None
            _finalize_login(cred, from_qr=True)


@click.command()
def logout() -> None:
    """清除已保存的登录凭证"""
    from ..auth import clear_credential
    clear_credential()
    console.print("[green]✅ 已退出登录[/green]")


@click.command()
@structured_output_options
def status(as_json: bool, as_yaml: bool) -> None:
    """查看当前登录状态"""
    from ..auth import get_credential, verify_credential_details
    cred = get_credential()
    if cred:
        cookie_names = sorted(cred.cookies.keys())
        health = verify_credential_details(cred)
        authenticated = health["authenticated"]
        message = health.get("reason")
        data = {
            "credential_present": True,
            "cookie_count": len(cred.cookies),
            "cookies": cookie_names,
            **health,
        }
        if as_json:
            click.echo(json.dumps(data, indent=2, ensure_ascii=False))
        elif as_yaml:
            try:
                import yaml
                click.echo(yaml.dump(data, allow_unicode=True))
            except ImportError:
                click.echo(json.dumps(data, indent=2, ensure_ascii=False))
        else:
            n = len(cred.cookies)
            keys = ", ".join(cookie_names[:5])
            extra = f" (+{n - 5} more)" if n > 5 else ""
            if authenticated:
                console.print(f"[green]✅ 已登录[/green] ({n} cookies)")
                console.print(f"  [dim]{keys}{extra}[/dim]")
            else:
                console.print(f"[yellow]⚠️  本地存在凭证，但登录态无效[/yellow] ({n} cookies)")
                console.print(f"  [dim]{keys}{extra}[/dim]")
            console.print(
                "  [dim]"
                f"search={'ok' if health['search_authenticated'] else 'fail'} · "
                f"recommend={'ok' if health['recommend_authenticated'] else 'fail'}"
                "[/dim]"
            )
            if message:
                console.print(f"  [dim]{message}[/dim]")
    else:
        if as_json:
            click.echo(json.dumps({"authenticated": False, "credential_present": False}))
        elif as_yaml:
            data = {"authenticated": False, "credential_present": False}
            try:
                import yaml
                click.echo(yaml.dump(data, allow_unicode=True))
            except ImportError:
                click.echo(json.dumps(data, indent=2, ensure_ascii=False))
        else:
            console.print("[yellow]⚠️  未登录[/yellow]，使用 [bold]boss login[/bold] 扫码登录")


@click.command()
@click.option("--basic", is_flag=True, help="只查看基本信息（不拉取在线简历详情）")
@structured_output_options
def me(basic: bool, as_json: bool, as_yaml: bool) -> None:
    """查看个人资料和在线简历（工作/项目/教育经历、个人优势、求职期望）"""
    cred = require_auth()

    def _action(client) -> dict:
        if basic:
            return client.get_resume_baseinfo()
        detail = client.get_resume_detail()
        base = detail.get("baseInfo") if isinstance(detail, dict) else None
        return {**(base if isinstance(base, dict) else {}), "resume": normalize_resume(detail)}

    def _render(info: dict) -> None:
        name = info.get("name", info.get("nickName", "-"))
        age = info.get("age", "-")
        degree = info.get("degreeCategory", "-")
        account = info.get("account", "-")
        gender = "男" if info.get("gender") == 1 else "女" if info.get("gender") == 2 else "-"
        work_years = info.get("workYearDesc")

        panel = Panel(
            f"[bold]{escape(str(name))}[/bold]  {gender}  {escape(str(age))}\n"
            f"学历: {escape(str(degree))}" + (f"  ·  {escape(work_years)}" if work_years else "") + "\n"
            f"账号: {escape(str(account))}",
            title="👤 个人资料",
            border_style="cyan",
        )
        console.print(panel)
        if "resume" in info:
            _render_resume(info["resume"])

    handle_command(
        cred,
        action=_action,
        render=_render,
        as_json=as_json,
        as_yaml=as_yaml,
    )


def _render_resume(resume: dict) -> None:
    if not resume:
        console.print("[yellow]⚠️  在线简历为空，请先在 BOSS直聘 完善简历[/yellow]")
        return

    def _block(title: str, body: str) -> None:
        console.print(Panel(escape(body), title=title, border_style="blue", title_align="left"))

    if resume.get("advantage"):
        _block("💡 个人优势", resume["advantage"])
    if resume.get("professional_skill"):
        _block("🛠  专业技能", resume["professional_skill"])

    if resume.get("expectations"):
        table = Table(title="🎯 求职期望", show_lines=False)
        for column in ("职位", "城市", "薪资", "行业"):
            table.add_column(column)
        for item in resume["expectations"]:
            table.add_row(*(escape(item.get(key, "-")) for key in ("position", "city", "salary", "industry")))
        console.print(table)

    for item in resume.get("work_experience", []):
        heading = "  ·  ".join(v for v in (item.get("company"), item.get("position"), item.get("period")) if v)
        body = "\n\n".join(
            f"{label}：{item[key]}"
            for key, label in (("department", "部门"), ("skills", "技能标签"), ("content", "工作内容"), ("performance", "工作业绩"))
            if item.get(key)
        )
        console.print(Panel(escape(body or "-"), title=f"💼 {escape(heading)}", border_style="green", title_align="left"))

    for item in resume.get("project_experience", []):
        heading = "  ·  ".join(v for v in (item.get("name"), item.get("role"), item.get("period")) if v)
        body = "\n\n".join(
            f"{label}：{item[key]}" for key, label in (("description", "项目描述"), ("performance", "项目业绩")) if item.get(key)
        )
        console.print(Panel(escape(body or "-"), title=f"📁 {escape(heading)}", border_style="magenta", title_align="left"))

    if resume.get("education"):
        table = Table(title="🎓 教育经历")
        for column in ("学校", "专业", "学历", "时间"):
            table.add_column(column)
        for item in resume["education"]:
            table.add_row(*(escape(item.get(key, "-")) for key in ("school", "major", "degree", "period")))
        console.print(table)

    if resume.get("certifications"):
        console.print(f"📜 资格证书: {escape('、'.join(resume['certifications']))}")
    if resume.get("last_update"):
        console.print(f"[dim]简历更新时间: {escape(resume['last_update'])}[/dim]")
